# Generated by Django 2.2.14 on 2022-03-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220324_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='image3',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
