# Generated by Django 2.2.14 on 2022-03-28 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_orderitem_uservar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='uservar',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='generate_name',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='var', to='core.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='generate_name',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='var', to=settings.AUTH_USER_MODEL),
        ),
    ]
