# Generated by Django 2.2.14 on 2022-03-28 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile_test_foreign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='generate_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='generate_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='test_foreign',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
