# Generated by Django 2.2.14 on 2023-02-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220328_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sku',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
