# Generated by Django 2.2.14 on 2023-02-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_orderitem_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='telephone',
            field=models.CharField(max_length=15),
        ),
    ]
